/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPage;

/**
 *
 * @author USER
 */
public class Dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form userDashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("BARANGAY TIMESHEET MANAGEMENT SYSTEM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 40, 570, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(230, 0, 610, 130);

        jPanel3.setBackground(new java.awt.Color(22, 123, 123));
        jPanel3.setLayout(null);

        jPanel7.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPage/ch.png"))); // NOI18N
        jLabel10.setText(" CHAT");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(10, 10, 160, 70);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(10, 150, 170, 80);

        jPanel8.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPage/home.png"))); // NOI18N
        jLabel9.setText(" HOME");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(0, -10, 170, 90);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(10, 50, 170, 70);

        jPanel9.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("DEVICES");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(10, 0, 100, 40);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(10, 350, 110, 40);

        jPanel10.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPage/feedb.png"))); // NOI18N
        jLabel12.setText(" FEEDBACK");
        jPanel10.add(jLabel12);
        jLabel12.setBounds(10, 0, 170, 60);

        jPanel3.add(jPanel10);
        jPanel10.setBounds(10, 260, 190, 70);

        jPanel11.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPage/andriod.png"))); // NOI18N
        jLabel14.setText(" ANDRIOD");
        jPanel11.add(jLabel14);
        jLabel14.setBounds(10, 0, 150, 50);

        jPanel3.add(jPanel11);
        jPanel11.setBounds(40, 400, 160, 50);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPage/laptop.png"))); // NOI18N
        jLabel11.setText("LAPTOP");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel12);
        jPanel12.setBounds(40, 460, 160, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 210, 530);

        jPanel4.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPage/pp.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 10, 180, 200);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("MANAGE USER");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 220, 150, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(250, 180, 190, 270);

        jPanel5.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPage/rep.png"))); // NOI18N
        jPanel5.add(jLabel3);
        jLabel3.setBounds(20, 20, 160, 190);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("REPORTS");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(50, 220, 100, 40);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(450, 180, 190, 270);

        jPanel6.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPage/set.png"))); // NOI18N
        jPanel6.add(jLabel4);
        jLabel4.setBounds(0, 20, 200, 190);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("SETTINGS");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(50, 220, 100, 40);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(650, 180, 190, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
